Homework3
made-mlops-2022/alexander_gamarnik pull request #3
Opened 2022-12-03 15:38 UTC by alexwerben

![airflow.jpg](screenshot/airflow.jpg)
Основная часть:

- [ ] Поднимите airflow локально, используя docker compose (можно использовать из примера https://github.com/made-ml-in-prod-2021/airflow-examples/)

- [ ] Реализуйте dag, который генерирует данные для обучения модели  (5 баллов)

- [ ] Реализуйте dag, который обучает модель еженедельно, используя данные за текущий день. (10 баллов)

- [ ] Реализуйте dag, который использует модель ежедневно (5 баллов)

- [ ] все даги реализованы только с помощью DockerOperator  (10 баллов)

- [ ] Традиционно, самооценка (1 балл)

- [ ] Дополнительная часть:

- [ ] Реализуйте сенсоры на то, что данные готовы для дагов тренировки и обучения (+3 доп балла)

2022-12-06 05:33 UTC, bulaevvi requested changes
Приложенные Вами скриншоты не подойдут. Сделайте пожалуйста так, как приведено в моем примере в дискорде https://discord.com/channels/681511874449244211/1011956997790380123/1049258596866727946

Обновленные скриншоты приведите в здесь, в комментариях к PR

2022-12-06 19:47 UTC, alex-werben commented
Добавляю скриншоты в соответствие с примером в Discord.
![alt](https://github.com/made-mlops-2022/alexander_gamarnik/blob/homework3/airflow_ml_dags/screenshot/dags.jpg?raw=true)
![alt](https://github.com/made-mlops-2022/alexander_gamarnik/blob/homework3/airflow_ml_dags/screenshot/generator.jpg?raw=true)
![alt](https://github.com/made-mlops-2022/alexander_gamarnik/blob/homework3/airflow_ml_dags/screenshot/train.jpg?raw=true)
![alt](https://github.com/made-mlops-2022/alexander_gamarnik/blob/homework3/airflow_ml_dags/screenshot/predict.jpg?raw=true)

2022-12-07 03:52 UTC, bulaevvi commented
Нижние три скриншота нормальные, но на верхнем (общем) видно, что второй и третий даги падали (судя по красным кружочкам). Надо разобраться, почему они падали, и добиться такого результата, чтобы все выполнялось нормально

Обратите внимание, что в приведенном мною дискордовском примере падений не было

2022-12-07 10:00 UTC, alexwerben commented
Все верно, падения были, когда отлаживал работу дагов в процессе написания кода. После этого историю не чистил, поэтому красные кружочки остались. Могу сбросить всю историю, чтобы от них избавиться.

2022-12-07 10:31 UTC, bulaevvi approved these changes
Итого 31 балл. Делайте merge

2022-12-07 10:54 UTC, merged